# Generated by Django 5.0.4 on 2024-05-01 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientconnection',
            name='media_id',
        ),
        migrations.AddField(
            model_name='clientconnection',
            name='source_id',
            field=models.PositiveIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clientconnection',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='WordPressConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_id', models.CharField(max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.client')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.connection')),
            ],
        ),
        migrations.CreateModel(
            name='YouTubeConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_id', models.CharField(max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.client')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.connection')),
            ],
        ),
    ]
