# Generated by Django 5.0.4 on 2024-05-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_remove_clientconnection_media_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordpressconnection',
            name='connection',
        ),
        migrations.RemoveField(
            model_name='youtubeconnection',
            name='connection',
        ),
        migrations.AlterField(
            model_name='connection',
            name='name',
            field=models.CharField(choices=[('YouTube', 'YouTube'), ('WordPress', 'WordPress')], max_length=20),
        ),
    ]
