# Generated by Django 5.0.4 on 2024-05-01 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_alter_connection_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=50, unique=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.youtubeconnection')),
            ],
        ),
    ]
