# Generated by Django 5.0.4 on 2024-05-01 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_youtubevideos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youtubevideos',
            old_name='playlist',
            new_name='connection',
        ),
        migrations.AddField(
            model_name='youtubevideos',
            name='transcribed',
            field=models.BooleanField(default=False),
        ),
    ]
