# Generated by Django 5.0.4 on 2024-05-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_rename_playlist_youtubevideos_connection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubevideos',
            name='connection',
        ),
        migrations.AddField(
            model_name='youtubevideos',
            name='playlist_id',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
