# Generated by Django 5.0.4 on 2024-05-02 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0007_remove_youtubevideos_connection_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YouTubeVideos',
        ),
    ]
