# Generated by Django 5.0.4 on 2024-05-02 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0008_delete_youtubevideos'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_id', models.CharField(max_length=100)),
                ('video_id', models.CharField(max_length=50, unique=True)),
                ('transcribed', models.BooleanField(default=False)),
            ],
        ),
    ]
