# Generated by Django 5.0.4 on 2024-05-08 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0010_llm_llmconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmconnection',
            name='bucket',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
