version: '3.8'

services:
  interface:
    image: interface:latest
    networks:
      - airflow_summit_network
    ports:
      - "8081:8081"
    volumes:
      - .:/app  # Mount local service directory into the container
    command: python manage.py runserver 0.0.0.0:8081

networks:
  airflow_summit_network:
    external: true  # Use an existing external network