version: '3.8'
networks:
  default:
    name: airflow_summit_network
    external: true
services:
  webapp:
    build: .
    ports:
      - "8081:8081"
    volumes:
      - ./app:/app  # Mount local app directory into the container
    command: uvicorn main:app --host 0.0.0.0 --port 8081 --reload
